"""Type stubs for a2a_client_async module."""

from typing import Optional, List, Dict, Any, Callable, Coroutine
import aiosqlite

class A2AClientAsync:
    project: str
    agent_id: str
    db_path: Any

    def __init__(self, project: str, agent_id: str) -> None: ...
    async def _connect(self) -> aiosqlite.Connection: ...
    async def close(self) -> None: ...
    async def send(
        self, to: str, message: str, ttl_seconds: Optional[int] = None
    ) -> int: ...
    async def recv(
        self,
        wait: int = 0,
        unread_only: bool = True,
        include_self: bool = False,
        limit: Optional[int] = None,
    ) -> List[Dict[str, Any]]: ...
    async def peek(self, limit: int = 10) -> List[Dict[str, Any]]: ...
    async def search(self, query: str, limit: int = 100) -> List[Dict[str, Any]]: ...
    async def thread(self, thread_id: str) -> List[Dict[str, Any]]: ...
    async def list_peers(self) -> List[Dict[str, Any]]: ...
    async def set_status(self, status: str) -> None: ...
    async def get_status(self, agent_id: Optional[str] = None) -> Optional[str]: ...
    async def stats(self) -> Dict[str, Any]: ...
    async def wait_for_messages(
        self, count: int = 1, timeout: int = 30
    ) -> List[Dict[str, Any]]: ...
    async def __aenter__(self) -> "A2AClientAsync": ...
    async def __aexit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

async def run_agent(
    agent_id: str,
    project: str,
    handler: Callable[[A2AClientAsync], Coroutine[Any, Any, None]],
) -> None: ...

async def run_agents(
    agents: List[tuple],
    handler: Callable[[A2AClientAsync], Coroutine[Any, Any, None]],
) -> None: ...
