"""Type stubs for a2a_client module."""

from typing import Optional, List, Dict, Any
import sqlite3

class A2AClient:
    project: str
    agent_id: str
    db_path: Any

    def __init__(self, project: str, agent_id: str) -> None: ...
    def _connect(self) -> sqlite3.Connection: ...
    def send(self, to: str, message: str, ttl_seconds: Optional[int] = None, thread_id: Optional[str] = None) -> int: ...
    def recv(
        self,
        wait: int = 0,
        unread_only: bool = True,
        include_self: bool = False,
        limit: Optional[int] = None,
    ) -> List[Dict[str, Any]]: ...
    def peek(self, limit: int = 20) -> List[Dict[str, Any]]: ...
    def search(self, query: str, limit: int = 100) -> List[Dict[str, Any]]: ...
    def thread(self, thread_id: str) -> List[Dict[str, Any]]: ...
    def list_peers(self) -> List[Dict[str, Any]]: ...
    def set_status(self, status: str) -> None: ...
    def get_status(self, agent_id: Optional[str] = None) -> Optional[str]: ...
    def stats(self) -> Dict[str, Any]: ...
    def wait_for_messages(
        self, count: int = 1, timeout: int = 30
    ) -> List[Dict[str, Any]]: ...
