"""Type stubs for a2a_client_async module."""

from typing import Optional, List, Dict, Any, Callable
import aiosqlite

class A2AClientAsync:
    project: str
    agent_id: str
    db_path: Any

    def __init__(self, project: str, agent_id: str) -> None: ...
    async def _connect(self) -> aiosqlite.Connection: ...
    async def close(self) -> None: ...
    async def register(
        self, role: str, prompt: str = "", cli: str = "", pid: Optional[int] = None, upsert: bool = True
    ) -> bool: ...
    async def unregister(self) -> bool: ...
    async def send(
        self, to: str, message: str, ttl_seconds: Optional[int] = None,
        thread_id: Optional[str] = None, priority: int = 3, require_ack: bool = False,
    ) -> int: ...
    async def recv(
        self,
        wait: float = 0,
        unread_only: bool = True,
        include_self: bool = False,
        limit: int = 0,
        priority_min: Optional[int] = None,
    ) -> List[Dict[str, Any]]: ...
    async def peek(self, limit: int = 20) -> List[Dict[str, Any]]: ...
    async def search(self, query: str, limit: int = 50) -> List[Dict[str, Any]]: ...
    async def thread(self, thread_id: str) -> List[Dict[str, Any]]: ...
    async def list(self) -> List[Dict[str, Any]]: ...
    async def list_peers(self) -> List[Dict[str, Any]]: ...
    async def set_status(self, status: str) -> None: ...
    async def get_status(self, agent_id: Optional[str] = None) -> Optional[str]: ...
    async def status(self, new_status: Optional[str] = None) -> Optional[str]: ...
    async def wait(self, count: int = 1, timeout: float = 60) -> bool: ...
    async def wait_for_messages(
        self, count: int = 1, timeout: float = 60
    ) -> bool: ...
    async def stats(self) -> Dict[str, Any]: ...
    async def ack(self, message_id: int) -> bool: ...
    async def pending_acks(self) -> List[Dict[str, Any]]: ...
    async def heartbeat(self, status: str = "active") -> None: ...
    async def heartbeat_check(self, grace: float = 120) -> List[Dict[str, Any]]: ...
    async def create_task(
        self, title: str, description: str = "", assigned_to: str = "",
        priority: int = 3, depends_on: Optional[List[int]] = None,
    ) -> int: ...
    async def list_tasks(self, status: Optional[str] = None, assigned_to: Optional[str] = None) -> List[Dict[str, Any]]: ...
    async def update_task_status(self, task_id: int, new_status: str) -> None: ...
    async def claim_task(self, task_id: int) -> None: ...
    async def complete_task(self, task_id: int, result: str = "") -> None: ...
    async def init_project(self) -> None: ...
    def project_info(self) -> Dict[str, Any]: ...
    async def clear(self) -> None: ...
    async def __aenter__(self) -> "A2AClientAsync": ...
    async def __aexit__(self, exc_type: Any, exc_val: Any, exc_tb: Any) -> None: ...

async def run_agent(
    agent_id: str,
    project: str,
    handler: Callable[..., Any],
) -> None: ...

async def run_agents(
    agents: List[tuple],
    handler: Callable[..., Any],
) -> None: ...
