"""Type stubs for a2a_client module."""

from typing import Optional, List, Dict, Any
import sqlite3

class A2AClient:
    project: str
    agent_id: str
    db_path: Any

    def __init__(self, project: str, agent_id: str) -> None: ...
    def _connect(self) -> sqlite3.Connection: ...
    def register(
        self, role: str, prompt: str = "", cli: str = "", pid: Optional[int] = None, upsert: bool = True
    ) -> bool: ...
    def unregister(self) -> bool: ...
    def send(self, to: str, message: str, ttl_seconds: Optional[int] = None, thread_id: Optional[str] = None) -> int: ...
    def recv(
        self,
        wait: float = 0,
        unread_only: bool = True,
        include_self: bool = False,
        limit: int = 0,
    ) -> List[Dict[str, Any]]: ...
    def peek(self, limit: int = 20) -> List[Dict[str, Any]]: ...
    def search(self, query: str, limit: int = 50) -> List[Dict[str, Any]]: ...
    def thread(self, thread_id: str) -> List[Dict[str, Any]]: ...
    def list(self) -> List[Dict[str, Any]]: ...
    def list_peers(self) -> List[Dict[str, Any]]: ...
    def set_status(self, status: str) -> None: ...
    def get_status(self, agent_id: Optional[str] = None) -> Optional[str]: ...
    def status(self, new_status: Optional[str] = None) -> Optional[str]: ...
    def wait(self, count: int = 1, timeout: float = 60) -> bool: ...
    def wait_for_messages(
        self, count: int = 1, timeout: float = 60
    ) -> bool: ...
    def stats(self) -> Dict[str, Any]: ...
    def init_project(self) -> None: ...
    def project_info(self) -> Dict[str, Any]: ...
    def clear(self) -> None: ...
